from fastapi import APIRouter, Request, HTTPException, BackgroundTasks
from twilio.twiml.messaging_response import MessagingResponse
from twilio.request_validator import RequestValidator
from app.config import settings
from app.agents.orchestrator import run_orchestrator
from app.utils.twilio_client import send_whatsapp_message, send_whatsapp_interactive
from app.utils.whatsapp_interactive import detect_interactive_prompt, extract_interactive_user_input
from app.utils.logger import logger

router = APIRouter()
validator = RequestValidator(settings.twilio_auth_token)

def _build_external_url_for_twilio(request: Request) -> str:
    """
    Build the externally-visible webhook URL for Twilio signature verification.
    This is important behind proxies/tunnels (for example ngrok) where request.url
    may otherwise resolve to internal HTTP.
    """
    forwarded_proto = request.headers.get("x-forwarded-proto")
    forwarded_host = request.headers.get("x-forwarded-host")
    host = forwarded_host or request.headers.get("host") or request.url.hostname
    scheme = forwarded_proto or request.url.scheme
    path = request.url.path
    query = request.url.query
    base = f"{scheme}://{host}{path}"
    return f"{base}?{query}" if query else base

def validate_twilio_request(request: Request, form_data: dict[str, str]) -> bool:
    """Validate incoming request is actually from Twilio."""
    if settings.debug:
        return True

    signature = request.headers.get("X-Twilio-Signature", "")
    url = _build_external_url_for_twilio(request)

    return validator.validate(url, form_data, signature)

async def process_message_background(user_id: str, message: str, media_url: str = None):
    try:
        # If there's a voice note, transcribe it first
        if media_url:
            from app.utils.voice_handler import transcribe_voice_note
            transcript = await transcribe_voice_note(media_url)
            if transcript:
                logger.info(f"Using voice transcript as message: {transcript}")
                message = transcript
            else:
                logger.warning("Voice transcription returned empty result.")
                send_whatsapp_message(user_id, "I heard your voice note but couldn't quite understand it. Could you try speaking again or typing it out?")
                return

        logger.info(f"Processing message natively for {user_id}")
        
        # result_message generated by orchestrator
        result_message = await run_orchestrator(user_id, message)
        
        # Send reply (interactive when possible, fallback to plain message)
        interactive = detect_interactive_prompt(result_message)
        if interactive:
            send_whatsapp_interactive(user_id, interactive)
        else:
            send_whatsapp_message(user_id, result_message)
        
    except Exception as exc:
        logger.error(f"Background task failed: {exc}")
        try:
            send_whatsapp_message(
                user_id,
                "I hit a temporary issue processing that. Please try again in a moment.",
            )
        except Exception:
            logger.error("Failed to send fallback error message", extra={"to": user_id})

@router.post("/webhook/whatsapp")
async def whatsapp_webhook(request: Request, background_tasks: BackgroundTasks):
    """Twilio WhatsApp webhook endpoint."""
    form = await request.form()
    form_data = {k: str(v) for k, v in form.items()}

    from_number = form_data.get("From", "")
    body = form_data.get("Body", "")
    media_url = form_data.get("MediaUrl0")
    button_text = form_data.get("ButtonText")
    button_payload = form_data.get("ButtonPayload")
    list_title = form_data.get("ListTitle")
    list_id = form_data.get("ListId")
    interactive_data = form_data.get("InteractiveData")

    logger.info(
        "WhatsApp webhook received",
        extra={"from": from_number, "has_media": bool(media_url), "body_length": len(body or "")},
    )

    is_valid = validate_twilio_request(request, form_data)
    if not is_valid:
        logger.warning(
            "Invalid Twilio signature",
            extra={"from": from_number, "url_checked": _build_external_url_for_twilio(request)},
        )
        raise HTTPException(status_code=403, detail="Invalid signature")

    incoming_message = extract_interactive_user_input(
        body=body,
        button_text=button_text,
        button_payload=button_payload,
        list_title=list_title,
        list_id=list_id,
        interactive_data=interactive_data,
    )
    logger.info("Received WhatsApp message", extra={"from": from_number, "body_length": len(incoming_message)})
    
    # Process message in Background
    background_tasks.add_task(process_message_background, from_number, incoming_message, media_url)
    
    # Return empty response to Twilio
    response = MessagingResponse()
    logger.info("Returning 200 to Twilio webhook", extra={"from": from_number})
    return str(response)
